### ISSUE TITLE
Correspondence between each label and 3 label.(Person Activity/Person + Object Activity/Person + Person Activity)

### ISSUE THREAD

**Issue by HayatoTanoue** [visym/cap#2]
In cap_histogram.png, three colors are displayed for Person Activity/Person + Object Activity/Person + Person Activity, but where can I check the correspondence of each label?

**Comment by jebyrne** [comment]
This information is not directly available in the release.  We have added a JSON file which exposes this mapping here:

https://github.com/visym/cap/blob/main/classification/cap_category_to_activitytype.json
