### ISSUE TITLE
Subject IDs in the dataset

### ISSUE THREAD

**Issue by ptirupat** [visym/cap#3]
Hello,

I see that there are subject IDs in the annotation files. Are they consistent across videos corresponding to the same subject? If they are, is there a way to read this information using the Vipy library?

**Comment by jebyrne** [comment]
Yes, the subject IDs are a globally unique identifier for each subject in a video, and are consistent across videos in all of our datasets.  However, please note that the subject IDs are self-reported by our worldwide collectors who recorded the video, and have not been independently verified by a review team.  So, they are likely to be noisy. 

To extract a list of subject IDs present in a video using the vipy python tools:

`# Load a list of annotated videos for a class, and print the list of subject IDs in the first video`  
`V = vipy.load('annotations/person_puts_down_object_on_bed.json')`  
`print(V[0].attributes['subject_ids'])`    

['936deb11-c258-4898-b5d3-d4264a87094b']
